#!/usr/bin/env node
/**
 * Vendor the juror logic this deployment reuses, byte for byte, into src/vendor/.
 *
 *   node scripts/sync-vendor.mjs          # copy sources -> src/vendor (commit the result)
 *   node scripts/sync-vendor.mjs --check  # exit 1 if src/vendor differs from the sources
 *
 * Why vendor: this Vercel project is deployed from a snapshot of services/jurors-vercel alone
 * (no monorepo install), and the juror modules must be the *same* code the reference juror
 * processes run: rubric/prompt, screening, verdict parsing, evidence auth, commitments,
 * rationale docs, model pins. Files are copied unchanged; `@envmarket/shared` resolves to
 * src/shared-lite.ts (tsconfig paths), which re-exports only the vendored shared modules.
 * The prompt is also emitted as a string module so its bytes (and sha256) survive bundling.
 */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const PKG = path.resolve(HERE, '..');
const ROOT = path.resolve(PKG, '../..');
const OUT = path.join(PKG, 'src', 'vendor');
const check = process.argv.includes('--check');

/** [source relative to repo root, destination relative to src/vendor] */
const FILES = [
  ...['commit', 'decide', 'evidence', 'llm', 'market', 'publish', 'rubric', 'state'].map((m) => [`services/jurors/src/${m}.ts`, `jurors/src/${m}.ts`]),
  ['services/jurors/prompts/juror-v1.md', 'jurors/prompts/juror-v1.md'],
  ['packages/shared/src/eip712.ts', 'shared/eip712.ts'],
  ['packages/shared/src/llm.ts', 'shared/llm.ts'],
  ['packages/shared/src/abi/EnvMarket.json', 'shared/abi/EnvMarket.json'],
  ['deployments/84532.json', 'deployments/84532.json'],
];

function generated() {
  const out = new Map();
  for (const [src, dst] of FILES) {
    const abs = path.join(ROOT, src);
    if (!existsSync(abs)) throw new Error(`missing source ${src}`);
    out.set(dst, readFileSync(abs));
  }
  const prompt = readFileSync(path.join(ROOT, 'services/jurors/prompts/juror-v1.md'));
  const sha = createHash('sha256').update(prompt).digest('hex');
  out.set(
    'prompt-text.ts',
    Buffer.from(
      `// GENERATED by scripts/sync-vendor.mjs from services/jurors/prompts/juror-v1.md. Do not edit.\n` +
        `export const PROMPT_VERSION = 'juror-v1';\n` +
        `export const PROMPT_SHA256 = '0x${sha}';\n` +
        `export const PROMPT_TEXT: string = ${JSON.stringify(prompt.toString('utf8'))};\n`,
    ),
  );
  return out;
}

function walk(dir, base = dir, acc = []) {
  if (!existsSync(dir)) return acc;
  for (const name of readdirSync(dir)) {
    const p = path.join(dir, name);
    if (statSync(p).isDirectory()) walk(p, base, acc);
    else acc.push(path.relative(base, p).split(path.sep).join('/'));
  }
  return acc;
}

const want = generated();
if (check) {
  const have = new Set(walk(OUT));
  const problems = [];
  for (const [rel, bytes] of want) {
    const p = path.join(OUT, rel);
    if (!existsSync(p)) problems.push(`missing ${rel}`);
    else if (!readFileSync(p).equals(bytes)) problems.push(`stale ${rel}`);
    have.delete(rel);
  }
  for (const rel of have) problems.push(`unexpected ${rel}`);
  if (problems.length) {
    console.error(`src/vendor is out of sync with its sources (run: npm run sync):\n  ${problems.join('\n  ')}`);
    process.exit(1);
  }
  console.log(`src/vendor in sync (${want.size} files)`);
} else {
  rmSync(OUT, { recursive: true, force: true });
  for (const [rel, bytes] of want) {
    const p = path.join(OUT, rel);
    mkdirSync(path.dirname(p), { recursive: true });
    writeFileSync(p, bytes);
  }
  console.log(`synced ${want.size} files into src/vendor`);
}
