[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
libs = ["node_modules"]
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 50
via_ir = true
remappings = [
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  "forge-std/=node_modules/forge-std/src/",
]
fs_permissions = [{ access = "read-write", path = "../deployments" }]

[lint]
lint_on_build = false

[fuzz]
runs = 256

[invariant]
runs = 64
depth = 64
fail_on_revert = false
