/**
 * Runtime ABI loader. The ABI JSON files (src/abi/EnvMarket.json, src/abi/TestUSDC.json) are
 * produced by the contracts build; this module reads them lazily so the package works before
 * they exist. Accepts either a bare ABI array or a Foundry artifact ({ abi: [...] }).
 */
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import * as path from 'node:path';
import type { Abi } from 'viem';

export type AbiName = 'EnvMarket' | 'TestUSDC';

export const ABI_DIR = fileURLToPath(new URL('./abi/', import.meta.url));

const cache = new Map<string, Abi>();

export function abiPath(name: AbiName | string): string {
  if (!/^[A-Za-z0-9_]+$/.test(name)) throw new Error(`bad ABI name ${name}`);
  return path.join(ABI_DIR, `${name}.json`);
}

export function hasAbi(name: AbiName | string): boolean {
  return existsSync(abiPath(name));
}

/** Load (and cache) an ABI by contract name. Throws a clear error if the file is missing. */
export function loadAbi(name: AbiName | string): Abi {
  const hit = cache.get(name);
  if (hit) return hit;
  const p = abiPath(name);
  if (!existsSync(p)) {
    throw new Error(`ABI ${name} not found at ${p} (generated by the contracts build: copy out/${name}.sol/${name}.json abi)`);
  }
  const parsed: unknown = JSON.parse(readFileSync(p, 'utf8'));
  const abi = Array.isArray(parsed) ? parsed : (parsed as { abi?: unknown }).abi;
  if (!Array.isArray(abi)) throw new Error(`ABI file ${p} has no ABI array`);
  cache.set(name, abi as Abi);
  return abi as Abi;
}
