#!/usr/bin/env bash
# Sync contract ABIs and deployment addresses into the standalone web app (apps/web).
#
#   packages/shared/src/abi/*.json  -> apps/web/src/generated/abi/
#     (fallback: contracts/out/<Name>.sol/<Name>.json for EnvMarket and TestUSDC)
#   deployments/*.json              -> apps/web/src/generated/deployments/
#
# It then regenerates apps/web/src/generated/contracts.ts, a typed (`as const`) module the app
# imports. The web app deliberately does not depend on packages/shared. Run this from anywhere
# whenever the contracts are rebuilt or redeployed, then commit apps/web/src/generated.
set -euo pipefail
shopt -s nullglob

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_ABI="$ROOT/packages/shared/src/abi"
SRC_OUT="$ROOT/contracts/out"
SRC_DEP="$ROOT/deployments"
OUT="$ROOT/apps/web/src/generated"

mkdir -p "$OUT/abi" "$OUT/deployments"
rm -f "$OUT/abi/"*.json "$OUT/deployments/"*.json

abi_files=("$SRC_ABI"/*.json)
if ((${#abi_files[@]})); then
  cp "${abi_files[@]}" "$OUT/abi/"
  echo "synced ${#abi_files[@]} ABI file(s) from packages/shared/src/abi"
else
  n=0
  for name in EnvMarket TestUSDC; do
    art="$SRC_OUT/$name.sol/$name.json"
    if [[ -f "$art" ]]; then
      # EnvMarket delegatecalls EnvMarketViews for read-only functions, so its callable ABI is
      # the union of both artifacts (views are called on the EnvMarket address).
      node -e '
        const fs = require("fs");
        const [art, views, out] = process.argv.slice(1);
        const abi = JSON.parse(fs.readFileSync(art, "utf8")).abi;
        if (views && fs.existsSync(views)) {
          const key = (x) => `${x.type}:${x.name ?? ""}:${(x.inputs ?? []).map((i) => i.type).join(",")}`;
          const seen = new Set(abi.map(key));
          for (const x of JSON.parse(fs.readFileSync(views, "utf8")).abi) {
            if (x.type === "constructor" || seen.has(key(x))) continue;
            abi.push(x);
            seen.add(key(x));
          }
        }
        fs.writeFileSync(out, JSON.stringify(abi, null, 2) + "\n");
      ' "$art" "$([[ $name == EnvMarket ]] && echo "$SRC_OUT/EnvMarketViews.sol/EnvMarketViews.json")" "$OUT/abi/$name.json"
      n=$((n + 1))
    fi
  done
  if ((n)); then
    echo "synced $n ABI file(s) from contracts/out (packages/shared/src/abi is empty)"
  else
    echo "warning: no ABI found (web app falls back to the ABI transcribed from the spec)"
  fi
fi

dep_files=("$SRC_DEP"/*.json)
if ((${#dep_files[@]})); then
  cp "${dep_files[@]}" "$OUT/deployments/"
  echo "synced ${#dep_files[@]} deployment file(s) from deployments/"
else
  echo "warning: no deployment files in deployments/ (web app will show 'not deployed')"
fi

node - "$OUT" <<'NODE'
const fs = require("fs");
const path = require("path");
const out = process.argv[2];
const read = (dir) =>
  fs.readdirSync(path.join(out, dir)).filter((f) => f.endsWith(".json")).sort()
    .map((f) => [path.basename(f, ".json"), JSON.parse(fs.readFileSync(path.join(out, dir, f), "utf8"))]);

const abis = read("abi").map(([name, json]) => [name, Array.isArray(json) ? json : json.abi]).filter(([, a]) => Array.isArray(a));
const deps = read("deployments");
const ident = (s) => s.replace(/[^A-Za-z0-9_]/g, "_");

let ts = "// AUTO-GENERATED by scripts/sync-web.sh. Do not edit by hand.\n\n";
for (const [name, abi] of abis) ts += `export const ${ident(name)}Abi = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
ts += "export const generatedAbis: Record<string, readonly unknown[]> = {\n";
for (const [name] of abis) ts += `  ${JSON.stringify(name)}: ${ident(name)}Abi,\n`;
ts += "};\n\n";
ts += "export const generatedDeployments: Record<string, Record<string, unknown>> = {\n";
for (const [name, json] of deps) ts += `  ${JSON.stringify(String(json.chainId ?? name))}: ${JSON.stringify(json)},\n`;
ts += "};\n";
fs.writeFileSync(path.join(out, "contracts.ts"), ts);
console.log(`wrote apps/web/src/generated/contracts.ts (${abis.length} ABI(s), ${deps.length} deployment(s))`);
NODE
