/**
 * GET /api/attestation/verify[?versionId=<id>]: third-party check of the TEE's Phala Cloud
 * (dstack, Intel TDX) attestation, run on this app's server.
 *
 * It runs server-side because Phala's public quote verifier
 * (POST https://cloud-api.phala.com/api/v1/attestations/verify {hex}) sends no CORS headers.
 * Nothing here trusts the TEE's own claims. Every check recomputes from the raw quote, event log and
 * app-compose that the TEE serves at /attestation, from the chain, or from the published deployment record:
 *   1. quote: Phala's verifier checks the Intel DCAP signature chain and TCB (quote.verified).
 *   2. report_data (quote bytes 568..632) = sha512(binding), and the verifier's parsed body agrees.
 *   3. binding: canonical JSON naming this app's chain id and market, the app id, and the signer.
 *   4. RTMR3: every event digest recomputed, then replayed = the quote's RTMR3. The app-id and
 *      compose-hash events equal the app id and sha256(app-compose).
 *   5. image: app-compose pins every image by digest, and composeHash / imageDigest / appId equal
 *      deployments/phala-tee.json (synced into src/generated by scripts/sync-web.sh).
 *   6. roles: binding.signer holds isRunner / isRelay / isVerifier, read from the chain here.
 *   7. (?versionId) the report's own quote verifies, with report_data =
 *      sha512(canonical {type: "envmarket.report.attestation.v1", versionId, reportHash}).
 */
import { createHash } from "node:crypto";
import canonicalize from "canonicalize";
import type { NextRequest } from "next/server";
import { createPublicClient, getAddress, http, isAddress } from "viem";
import { marketAbi } from "@/lib/abi";
import { CHAIN_ID, chain, deployment, RPC_URL } from "@/lib/config";
import { generatedDeployments } from "@/generated/contracts";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60;

const PHALA_VERIFY_API = "https://cloud-api.phala.com/api/v1/attestations/verify";
const TRUST_CENTER = "https://trust.phala.com/app";
/** TDX quote v4: 48-byte header + TD report; RTMR3 at 520..568, report_data at 568..632. */
const RTMR3_OFF = 520;
const RD_OFF = 568;

type Check = { id: string; label: string; ok: boolean | null; detail?: string };
type EventLogEntry = { imr: number; event_type: number; digest: string; event: string; event_payload: string };
export type AttestationVerifyResult = {
  vendor: string | null;
  kind: string;
  appId: string | null;
  signer: string | null;
  trustUrl: string | null;
  verifyApi: string;
  quoteDigest: string | null;
  composeHash: string | null;
  imageDigest: string | null;
  ok: boolean;
  checks: Check[];
  report: { versionId: string; reportHash: string } | null;
  checkedAt: string;
};

const sha = (alg: "sha256" | "sha384" | "sha512", data: Buffer | string) => createHash(alg).update(data).digest();
const hex = (s: unknown) => String(s ?? "").replace(/^0x/, "").toLowerCase();
const short = (s: string) => (s.length > 20 ? `${s.slice(0, 16)}…` : s);
const errMsg = (e: unknown) => (e instanceof Error ? e.message : String(e));

function teeBase(): string | null {
  const u = (process.env.TEE_URL || process.env.NEXT_PUBLIC_TEE_URL || "").replace(/\/+$/, "");
  return /^https?:\/\//.test(u) ? u : null;
}

async function getJson<T = Record<string, unknown>>(url: string, init?: RequestInit): Promise<T> {
  const r = await fetch(url, { ...init, cache: "no-store", signal: AbortSignal.timeout(45_000) });
  const text = await r.text();
  if (!r.ok) throw new Error(`${r.status} ${text.slice(0, 200)}`);
  return JSON.parse(text) as T;
}

type Verdict = { verified: boolean; reportData: string | null; rtmr3: string | null };
async function phalaVerify(quote: string): Promise<Verdict> {
  const d = await getJson<{ quote?: { verified?: boolean; body?: { reportdata?: string; rtmr3?: string } } }>(PHALA_VERIFY_API, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ hex: quote }),
  });
  const q = d.quote ?? {};
  return { verified: q.verified === true, reportData: q.body?.reportdata ? hex(q.body.reportdata) : null, rtmr3: q.body?.rtmr3 ? hex(q.body.rtmr3) : null };
}

/** dstack runtime event digest: sha384(u32le(event_type) ‖ ":" ‖ event ‖ ":" ‖ payload bytes). */
function eventDigest(e: EventLogEntry): string {
  const t = Buffer.alloc(4);
  t.writeUInt32LE(e.event_type >>> 0);
  return sha("sha384", Buffer.concat([t, Buffer.from(":"), Buffer.from(e.event, "utf8"), Buffer.from(":"), Buffer.from(e.event_payload, "hex")])).toString("hex");
}

/**
 * Replay an RTMR. dstack 0.5.9 serves RTMR3 events with an EMPTY digest field; the verifier must
 * recompute each digest from (event_type, event, payload), which binds the payloads (app-id,
 * compose-hash, os-image-hash, ...) to the quote. A digest that is present must match the recomputed one.
 */
function replayRtmr(events: EventLogEntry[]): string {
  let mr = Buffer.alloc(48);
  for (const e of events) {
    let d = Buffer.from(e.digest ? hex(e.digest) : eventDigest(e), "hex");
    if (d.length < 48) d = Buffer.concat([d, Buffer.alloc(48 - d.length)]);
    mr = sha("sha384", Buffer.concat([mr, d]));
  }
  return mr.toString("hex");
}

const slice = (quote: string, off: number, len: number) => quote.slice(off * 2, (off + len) * 2);

export async function GET(req: NextRequest): Promise<Response> {
  const base = teeBase();
  if (!base) return Response.json({ error: "TEE service is not configured on this deployment (set TEE_URL)" }, { status: 503 });
  let att: Record<string, unknown>;
  try {
    att = await getJson(`${base}/attestation`);
  } catch (e) {
    return Response.json({ error: `TEE /attestation unreachable: ${errMsg(e)}` }, { status: 502 });
  }

  const checks: Check[] = [];
  const add = (id: string, label: string, ok: boolean | null, detail?: string) => checks.push({ id, label, ok, detail });
  const kind = String(att.kind ?? "unknown");
  const appId = typeof att.appId === "string" ? att.appId.toLowerCase() : null;
  const result = (extra: Partial<AttestationVerifyResult>): Response =>
    Response.json(
      {
        vendor: (att.vendor as string) ?? null,
        kind,
        appId,
        signer: (att.signer as string) ?? null,
        trustUrl: appId ? `${TRUST_CENTER}/${appId}` : null,
        verifyApi: PHALA_VERIFY_API,
        quoteDigest: (att.quoteDigest as string) ?? null,
        composeHash: (att.composeHash as string) ?? null,
        imageDigest: null,
        ok: checks.length > 0 && checks.every((c) => c.ok !== false) && checks.some((c) => c.ok === true),
        checks,
        report: null,
        checkedAt: new Date().toISOString(),
        ...extra,
      } satisfies AttestationVerifyResult,
      { headers: { "cache-control": "public, max-age=30" } },
    );

  if (kind !== "phala-dstack-tdx") {
    add("kind", "TEE serves a Phala dstack TDX attestation", false, `attestation.kind = ${kind}`);
    return result({});
  }

  // 1 + 2: genuine quote, report_data = sha512(binding)
  const quote = hex(att.quote ?? att.token);
  const binding = String(att.binding ?? "");
  const expectedRd = sha("sha512", binding).toString("hex");
  let verdict: Verdict | null = null;
  try {
    verdict = await phalaVerify(quote);
    add("quote", "Intel TDX quote verified by Phala's public verifier (Intel DCAP signature chain and TCB)", verdict.verified, verdict.verified ? undefined : "quote.verified = false");
  } catch (e) {
    add("quote", "Intel TDX quote verified by Phala's public verifier (Intel DCAP signature chain and TCB)", false, `verifier error: ${errMsg(e)}`);
  }
  const rawRd = slice(quote, RD_OFF, 64);
  const rdOk = rawRd === expectedRd && hex(att.reportData) === expectedRd && (!verdict?.reportData || verdict.reportData === expectedRd);
  add("reportData", "Quote report_data = sha512(binding)", rdOk, rdOk ? `sha512 = ${short(expectedRd)}` : `quote ${short(rawRd)} vs sha512(binding) ${short(expectedRd)}`);
  add("quoteDigest", "quoteDigest = sha256(quote bytes)", `0x${sha("sha256", Buffer.from(quote, "hex")).toString("hex")}` === String(att.quoteDigest ?? "").toLowerCase());

  // 3: what the binding commits to
  let b: Record<string, unknown> = {};
  try {
    b = JSON.parse(binding) as Record<string, unknown>;
  } catch {
    /* reported below */
  }
  const bindingOk =
    canonicalize(b) === binding &&
    b.type === "envmarket.tee.binding.v1" &&
    b.vendor === "phala" &&
    b.chainId === CHAIN_ID &&
    !!deployment &&
    String(b.market).toLowerCase() === deployment.market.toLowerCase() &&
    String(b.appId).toLowerCase() === appId &&
    String(b.signer).toLowerCase() === String(att.signer ?? "").toLowerCase();
  add("binding", "Binding names this chain, this market, the app id and the signer", bindingOk, `chainId ${String(b.chainId)} · market ${String(b.market)} · signer ${String(b.signer)}`);

  // 4: RTMR3 replay, app-id and compose-hash events
  const events: EventLogEntry[] = Array.isArray(att.eventLog) ? (att.eventLog as EventLogEntry[]) : [];
  const r3 = events.filter((e) => e.imr === 3);
  const badDigest = r3.find((e) => !!e.digest && eventDigest(e) !== hex(e.digest));
  const quoteRtmr3 = slice(quote, RTMR3_OFF, 48);
  const replay = replayRtmr(r3);
  add(
    "rtmr3",
    "RTMR3 replayed from the event log (each digest recomputed) = the quote's RTMR3",
    r3.length > 0 && !badDigest && replay === quoteRtmr3 && (!verdict?.rtmr3 || verdict.rtmr3 === quoteRtmr3),
    badDigest ? `event ${badDigest.event} digest does not match its payload` : `${r3.length} events`,
  );
  const evPayload = (name: string) => hex(r3.find((e) => e.event === name)?.event_payload ?? "");
  const appCompose = typeof att.appCompose === "string" ? att.appCompose : "";
  const composeHash = hex(att.composeHash);
  add("appIdEvent", "RTMR3 app-id event = the attested app id", !!appId && evPayload("app-id") === appId);
  add(
    "composeHash",
    "sha256(app-compose) = composeHash = RTMR3 compose-hash event",
    !!appCompose && sha("sha256", appCompose).toString("hex") === composeHash && evPayload("compose-hash") === composeHash,
    short(composeHash),
  );

  // 5: image pinned by digest; matches the published deployment
  let dockerCompose = "";
  try {
    dockerCompose = String((JSON.parse(appCompose) as { docker_compose_file?: string }).docker_compose_file ?? "");
  } catch {
    /* empty → not pinned */
  }
  const images = [...dockerCompose.matchAll(/^\s*image:\s*(\S+)/gm)].map((m) => m[1]!.replace(/^["']|["']$/g, ""));
  const imageDigest = images[0]?.match(/@(sha256:[0-9a-f]{64})$/)?.[1] ?? null;
  add("imagePinned", "The attested compose pins every image by digest", images.length > 0 && images.every((i) => /@sha256:[0-9a-f]{64}$/.test(i)), images.join(", ") || "no image lines");
  const published = generatedDeployments["phala-tee"] as Record<string, unknown> | undefined;
  if (published) {
    const ok = hex(published.composeHash) === composeHash && published.imageDigest === imageDigest && String(published.appId).toLowerCase() === appId;
    add("published", "Compose hash, image digest and app id match the published deployment (deployments/phala-tee.json)", ok, `published ${short(hex(published.composeHash))} · ${String(published.imageDigest)}`);
  } else {
    add("published", "Compose hash, image digest and app id match the published deployment (deployments/phala-tee.json)", null, "no published deployment record in this web build");
  }

  // 6: the signer's on-chain roles, read here (not from the TEE)
  if (deployment && typeof b.signer === "string" && isAddress(b.signer)) {
    try {
      const client = createPublicClient({ chain, transport: http(RPC_URL) });
      const read = (functionName: string) =>
        client.readContract({ address: deployment!.market, abi: marketAbi, functionName, args: [getAddress(b.signer as string)] } as never) as Promise<boolean>;
      const [r, l, v] = await Promise.all([read("isRunner"), read("isRelay"), read("isVerifier")]);
      add("roles", "The attested signer is the on-chain runner, relay and verifier", r && l && v, `isRunner ${r} · isRelay ${l} · isVerifier ${v}`);
    } catch (e) {
      add("roles", "The attested signer is the on-chain runner, relay and verifier", false, `chain read failed: ${errMsg(e)}`);
    }
  } else {
    add("roles", "The attested signer is the on-chain runner, relay and verifier", false, "no market deployment or no signer in the binding");
  }

  // 7: the per-report quote
  let report: AttestationVerifyResult["report"] = null;
  const vid = req.nextUrl.searchParams.get("versionId");
  if (vid && /^\d{1,30}$/.test(vid)) {
    const label = "The report's own quote verifies, with report_data = sha512({type, versionId, reportHash})";
    try {
      const r = await getJson<{ reportHash?: string; attestationToken?: string | null }>(`${base}/reports/${vid}`);
      if (r.reportHash) report = { versionId: vid, reportHash: r.reportHash };
      const token = r.attestationToken ? hex(r.attestationToken) : null;
      if (!token || !r.reportHash) add("reportQuote", label, null, "this report carries no quote");
      else {
        const exp = sha("sha512", canonicalize({ type: "envmarket.report.attestation.v1", versionId: vid, reportHash: r.reportHash })!).toString("hex");
        const pv = await phalaVerify(token);
        const same = slice(token, RTMR3_OFF, 48) === quoteRtmr3;
        add("reportQuote", label, pv.verified && slice(token, RD_OFF, 64) === exp, `${pv.verified ? "verified" : "NOT verified"}; ${same ? "same" : "different"} RTMR3 as the running compose`);
      }
    } catch (e) {
      add("reportQuote", label, false, errMsg(e));
    }
  }

  return result({ imageDigest, report });
}
